### ISSUE TITLE
Margin loss does not decrease

### ISSUE THREAD

**Issue by bdqnghi** [XinyiZ001/CapsGNN#5]
Hi, the margin loss never decreases, only the reconstruction loss decrease, is there any explanation for this?

**Comment by XinyiZ001** [comment]
1.Training time is variable based on different datasets so your data may need to be trained for more steps before loss decreasing.
2.Initialization is a problem which is still not solved in this work. A better initialization could improve training efficiency.
3 if we take Enzymes as an example, the loss will not decrease until trained for 600 steps.
